# Generated by Django 4.1.7 on 2023-03-02 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('work_hours', models.FloatField(default=0.0)),
                ('image', models.ImageField(default='images/printer.png', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Fliament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PLA', 'PLA'), ('PET', 'PET'), ('ABS', 'ABS')], max_length=10)),
                ('color', models.CharField(choices=[('RED', 'CZERWONY'), ('BLUE', 'NIEBIESKI')], max_length=20)),
                ('quantity', models.FloatField(default=1000.0)),
                ('uid', models.IntegerField()),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printers.printer')),
            ],
        ),
    ]
